#!/usr/bin/env bash

OUTPUT=/tmp/capnproto

git clone https://github.com/afeldman/capnproto.git ${OUTPUT}
cd ${OUTPUT}/c++
autoreconf -i
./configure
make -j6 check
sudo make install

rm -Rf ${OUTPUT}
