#!/usr/bin/env bash

echo "***************************** purge old kernel ****************************"
sudo dnf remove "$(dnf repoquery --installonly --latest-limit 2 -q)"
echo "***************************** purge finish ****************************"
