#!/usr/bin/env bash

echo "***************************** purge old kernel ****************************"
dpkg --list 'linux-image*' | awk '{ if ($1=="ii") print $2}' | grep -v `uname -r` | while read -r line; do sudo apt-get -y purge $line; done
echo "***************************** purge finish ****************************"

sudo apt-get autoremove
echo "***************** grup update *************"
sudo update-grub
echo "***************** grup update finsih ************" 
sudo apt-get update
sudo apt-get upgrade -y
