#!/usr/bin/env bash

usage() {
    echo "$0 usage: [OPTION] Source Target"
}

CPUS=`nproc --all`

while getopts "hc:" opt
do
  case $opt in
    h)
        usage
        ;;
    c)
        CPUS=$OPTARG
        ;;
    *)
        usage
        ;;
  esac
done

echo "start copy with ${CPUS} cpu\`s"

shift $((OPTIND - 1))
src=$1
tgt=$2

echo "${src} -> ${tgt}"

rclone copy "${src}" "${tgt}" --progress --multi-thread-streams=${CPUS}

