#!/usr/bin/env bash

inputfile=$1
password=$2

if [[ -f ${inputfile} ]]; then
    # Extract the basename
    b="${inputfile%.*}"

    echo "convert ${inputfile} into pem"
    openssl pkcs12 -in "${inputfile}" -out "${b}.pem" -passin "${password}"

    echo "build cert from ${inputfile} "
    openssl pkcs12 -in "${inputfile}" -out "${b}_ca.pem" -cacerts -nokeys  -passin "${password}"
    openssl pkcs12 -in "${inputfile}" -out "${b}_client.pem" -clcerts -nokeys  -passin "${password}"
    openssl pkcs12 -in "${inputfile}" -out "${b}_key.pem" -nocerts  -passin "${password}"

else
    echo "no input file found: " ${inputfile} 
fi

