#!/usr/bin/env bash

json_dir="${1}"

for file in $(ls ${json_dir})
do
    json_path=$(realpath ${file})
    echo $(date) ":" "${json_path}" 2>&1
    cat <<< $(jq . "${json_path}") > "${json_path}"
done
