#!/usr/bin/env bash

service() {
    service_name=$1
    systemctl --user status --now "${service_name}.timer"
}

journal() {
    service_name=$1
    journalctl --user -xeu "${service_name}.service"
}

services() {
    systemctl list-unit-files --user --state=enabled
}

while getopts "aj:s:" options
do
    case ${options} in
        j)
           journal ${OPTARG} ;;
        s)
            service ${OPTARG} ;;
        a)
            services ;;
        :) echo "option -$OPTARG requires an argument"
            ;;
    esac
done
